from vetores import *
init_printing(use_unicode=False, wrap_line=False)
N = CoordSys3D('N')
t = Symbol('t')
a = Symbol('a') 
valor = math.pi / 2
# r = ((1*sin(1*t))*N.i) + ((-1*cos(1*t))*N.j) + ((-2*t)*N.k)
# r = ((0)*N.i) + ((t*sin(1*t))*N.j) + ((t**2*cos(1*t))*N.k)
# r = ((3*cos(1*t))*N.i) + ((3*sin(1*t))*N.j) + ((2*t)*N.k)
# r = ((0)*N.i) + ((t*sin(1*t))*N.j) + ((t**2*cos(t))*N.k)
# r = ((t*cos(1*t))*N.i) + ((t*sin(1*t))*N.j) + ((0)*N.k)
# r = ((1*cos(1*t))*N.i) + ((1*sin(1*t))*N.j) + ((2)*N.k)
r = ((2 * cos(math.pi * t)) * N.i) + ((2 * sin(math.pi * t)) * N.j) + ((-1*t) * N.k)
# r = ((t)*N.i) + (((2*(E**(t-1))))*N.j) + (((t**2))*N.k)
# r = ((1*cos(1*t))*N.i) + ((1*sin(1*t))*N.j) + ((t)*N.k)
# r = ((cos(t))*N.i) + ((sin(t))*N.j) + ((cos(2*t))*N.k)
# r = ((t)*N.i) + (((1 - t**2))*N.j) + ((t**3 + 1)*N.k)
# r = ((t)*N.i) + (((t**2)/2)*N.j) + (((t**3)/3)*N.k)
# r = ((t)*N.i) + (((t**2))*N.j) + (((t**3))*N.k)
# r = ((t)*N.i) + ((a*t**2)*N.j) + ((0)*N.k)
# # r = ((1)*N.i) + ((-2)*N.j) + ((1)*N.k)
rPrime, rPrimePrime = Prime(r), Prime2(r)
print("r': ", rPrime)
rPrimeModulo = rPrime.magnitude()
# rPrimeModulo = sqrt(rPrime & rPrime)
print("\n||r'||: ", (rPrimeModulo))
# rPrimePrime = simplify(rPrime.diff(t))
# rPrimePrimePrime = simplify(rPrimePrime.diff(t))
rArco = simplify(integrate(rPrimeModulo, t))
print("\n arco: ", rArco.subs(t, 1))
areaP = (areaUV(1, 1, 0, 0, 1, 1))
print(areaP)